plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

def mcVersion = project.findProperty('mcVersion') ?: '26.1'
version = project.mod_version
group = project.maven_group
def versions = [
		"26.1": [
				loader: "0.19.3",
				api: "0.145.1+26.1",
				malilib: "xGyGn0t9",
				litematica: "MRcKRVoi",
				modmenu: "18.0.0"
		],
		"26.1.1": [
				loader: "0.19.3",
				api: "0.145.4+26.1.1",
				malilib: "xGyGn0t9",
				litematica: "MRcKRVoi",
				modmenu: "18.0.0"
		],
		"26.1.2": [
				loader: "0.19.3",
				api: "0.155.2+26.1.2",
				malilib: "xGyGn0t9",
				litematica: "MRcKRVoi",
				modmenu: "18.0.0"
		],
		"26.2": [
				loader: "0.19.3",
				api: "0.157.0+26.2",
				malilib: "xKxhjDJ2",
				litematica: "jzraAo7b",
				modmenu: "20.0.1"
		]
]
def selected = versions[mcVersion]
if (selected == null) {
	throw new GradleException("Unsupported Minecraft version: ${mcVersion}")
}

repositories {
	maven { url 'https://masa.dy.fi/maven' }
	maven { url 'https://maven.terraformersmc.com/releases/' }
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
		content {
			includeGroup "maven.modrinth"
		}
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"bettereasyplace" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${mcVersion}"
	implementation "net.fabricmc:fabric-loader:${selected.loader}"
	implementation "maven.modrinth:GcWjdA9I:${selected.malilib}"//malilib
	implementation "maven.modrinth:bEpr0Arc:${selected.litematica}"//litematica
	implementation "com.terraformersmc:modmenu:${selected.modmenu}"
	implementation "net.fabricmc.fabric-api:fabric-api:${selected.api}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
