plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

def mcVersion = project.findProperty('mcVersion') ?: '1.21.9'
version = project.mod_version
group = project.maven_group
def versions = [
		"1.21.9": [
				loader: "0.19.3",
				api: "0.134.1+1.21.9",
				malilib: "VwmyInJJ",
				litematica: "c91sTAlP",
				modmenu: "16.0.1"
		],
		"1.21.10": [
				loader: "0.19.3",
				api: "0.138.4+1.21.10",
				malilib: "VwmyInJJ",
				litematica: "c91sTAlP",
				modmenu: "16.0.1"
		]
]
def selected = versions[mcVersion]
if (selected == null) {
	throw new GradleException("Unsupported Minecraft version: ${mcVersion}")
}

repositories {
	maven { url 'https://masa.dy.fi/maven' }
	maven { url 'https://maven.terraformersmc.com/releases/' }
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
		content {
			includeGroup "maven.modrinth"
		}
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"bettereasyplace" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${mcVersion}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${selected.loader}"
	modImplementation "maven.modrinth:GcWjdA9I:${selected.malilib}"//malilib
	modImplementation "maven.modrinth:bEpr0Arc:${selected.litematica}"//litematica
	modImplementation "com.terraformersmc:modmenu:${selected.modmenu}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${selected.api}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
