plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	maven { url 'https://masa.dy.fi/maven' }
	maven { url 'https://maven.terraformersmc.com/releases/' }
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
		content {
			includeGroup "maven.modrinth"
		}
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"bettereasyplace" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "maven.modrinth:GcWjdA9I:${project.malilib_version_id}"//malilib
	modImplementation "maven.modrinth:bEpr0Arc:${project.litematica_version_id}"//litematica
	modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

def buildCounterFile = file("$projectDir/build-counter.txt")
def buildNumber = 0
if (buildCounterFile.exists()) {
	buildNumber = buildCounterFile.text.trim().toInteger()
}
buildNumber++
buildCounterFile.text = buildNumber.toString()

remapJar {
	archiveFileName.set("${project.name}-${project.mod_version}+build${buildNumber}.jar")
}

remapSourcesJar {
	archiveFileName.set("${project.name}-${project.mod_version}+build${buildNumber}-sources.jar")
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
