# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.19.0
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.1.0+1.20.1
maven_group=me.lbb.bettereasyplace

# Dependencies
malilib_version=0.16.2
litematica_project_id=308892
litematica_file_id=4593296
modmenu_version=7.2.2
